project:
  type: website
  output-dir: docs

website:
  title: "GIS Coding Workshop"
  sidebar:
    title: "GIS Coding Workshop"
    id: mainnav
    # footer: "2025-07-17"
    contents:
      - text: "Week 3"
        href: w03/index.qmd
      - text: "Week 4"
        href: w04/index.qmd
      - text: "Week 5"
        href: w05/index.qmd
      - text: "Week 6"
        href: w06/index.qmd
      - text: "Week 6 Demo"
        href: w06-demo/index.qmd
      - text: "Week 7"
        href: w07/index.qmd
      - text: "Week 8"
        href: w08/index.qmd
      - text: "Week 9"
        href: w09/index.qmd
      - text: "Week 10"
        href: w10/index.qmd
      - text: "Week 12"
        href: w12/index.qmd
      - text: "Resources"
        href: resources.qmd
      - "---"
      - href: "https://jjacobs.me/ppol6805"
        text: "Course Homepage <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 80%;'></i>"
      - href: "https://georgetown.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=c20d8a0c-387a-4d76-8ba8-b35700c9ee1f"
        text: "Recordings <i class='bi bi-box-arrow-up-right ps-1' style='font-size: 80%;'></i>"

format:
  html:
    include-in-header:
      text: |
        <script src='sidebar.js'></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible+Next:ital,wght@0,200..800;1,200..800&display=swap" rel="stylesheet">
    theme:
      light:
        - flatly
        - assets/workshop.scss
        - assets/workshop-light.scss
      dark:
        - darkly
        - assets/workshop.scss
        - assets/workshop-dark.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true

